export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_RESET = "ADMIN_LOGIN_RESET";

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL";
export const ADMIN_LOGOUT_RESET = "ADMIN_LOGOUT_RESET";

export const ADMIN_FORGOT_PASSWORD_REQUEST = "ADMIN_FORGOT_PASSWORD_REQUEST";
export const ADMIN_FORGOT_PASSWORD_SUCCESS = "ADMIN_FORGOT_PASSWORD_SUCCESS";
export const ADMIN_FORGOT_PASSWORD_FAIL = "ADMIN_FORGOT_PASSWORD_FAIL";
export const ADMIN_FORGOT_PASSWORD_RESET = "ADMIN_FORGOT_PASSWORD_RESET";

export const ADMIN_RESET_PASSWORD_REQUEST = "ADMIN_RESET_PASSWORD_REQUEST";
export const ADMIN_RESET_PASSWORD_SUCCESS = "ADMIN_RESET_PASSWORD_SUCCESS";
export const ADMIN_RESET_PASSWORD_FAIL = "ADMIN_RESET_PASSWORD_FAIL";

export const ADMIN_GET_REQUEST = "ADMIN_GET_REQUEST";
export const ADMIN_GET_SUCCESS = "ADMIN_GET_SUCCESS";
export const ADMIN_GET_FAIL = "ADMIN_GET_FAIL";

export const ADMIN_APPROVE_REQUEST = "ADMIN_APPROVE_REQUEST";
export const ADMIN_APPROVE_SUCCESS = "ADMIN_APPROVE_SUCCESS";
export const ADMIN_APPROVE_FAIL = "ADMIN_APPROVE_FAIL";

export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";
