export const RESOURCE_ADD_REQUEST = "RESOURCE_ADD_REQUEST";
export const RESOURCE_ADD_SUCCESS = "RESOURCE_ADD_SUCCESS";
export const RESOURCE_ADD_FAIL = "RESOURCE_ADD_FAIL";
export const RESOURCE_ADD_RESET = "RESOURCE_ADD_RESET";

export const RESOURCE_GET_REQUEST = "RESOURCE_GET_REQUEST";
export const RESOURCE_GET_SUCCESS = "RESOURCE_GET_SUCCESS";
export const RESOURCE_GET_FAIL = "RESOURCE_GET_FAIL";
export const RESOURCE_GET_RESET = "RESOURCE_GET_RESET";

export const SCHEDULE_GET_REQUEST = "SCHEDULE_GET_REQUEST";
export const SCHEDULE_GET_SUCCESS = "SCHEDULE_GET_SUCCESS";
export const SCHEDULE_GET_FAIL = "SCHEDULE_GET_FAIL";
export const SCHEDULE_GET_RESET = "SCHEDULE_GET_RESET";

export const RESOURCE_REQ_REQUEST = "RESOURCE_REQ_REQUEST";
export const RESOURCE_REQ_SUCCESS = "RESOURCE_REQ_SUCCESS";
export const RESOURCE_REQ_FAIL = "RESOURCE_REQ_FAIL";
export const RESOURCE_REQ_RESET = "RESOURCE_REQ_RESET";

export const RESOURCE_ADMIN_GET_REQUEST = "RESOURCE_ADMIN_GET_REQUEST";
export const RESOURCE_ADMIN_GET_SUCCESS = "RESOURCE_ADMIN_GET_SUCCESS";
export const RESOURCE_ADMIN_GET_FAIL = "RESOURCE_ADMIN_GET_FAIL";
export const RESOURCE_ADMIN_GET_RESET = "RESOURCE_ADMIN_GET_RESET";

export const RESOURCE_ADMIN_GET_PARTICULAR_REQUEST =
  "RESOURCE_ADMIN_GET_PARTICULAR_REQUEST";
export const RESOURCE_ADMIN_GET_PARTICULAR_SUCCESS =
  "RESOURCE_ADMIN_GET_PARTICULAR_SUCCESS";
export const RESOURCE_ADMIN_GET_PARTICULAR_FAIL =
  "RESOURCE_ADMIN_GET_PARTICULAR_FAIL";
export const RESOURCE_ADMIN_GET_PARTICULAR_RESET =
  "RESOURCE_ADMIN_GET_PARTICULAR_RESET";

export const RESOURCE_EDIT_REQUEST = "RESOURCE_EDIT_REQUEST";
export const RESOURCE_EDIT_SUCCESS = "RESOURCE_EDIT_SUCCESS";
export const RESOURCE_EDIT_FAIL = "RESOURCE_EDIT_FAIL";
export const RESOURCE_EDIT_RESET = "RESOURCE_EDIT_RESET";

export const REPORT_GET_REQUEST = "REPORT_GET_REQUEST";
export const REPORT_GET_SUCCESS = "REPORT_GET_SUCCESS";
export const REPORT_GET_FAIL = "REPORT_GET_FAIL";

export const SCHEDULE_DELETE_REQUEST = "SCHEDULE_DELETE_REQUEST";
export const SCHEDULE_DELETE_SUCCESS = "SCHEDULE_DELETE_SUCCESS";
export const SCHEDULE_DELETE_FAIL = "SCHEDULE_DELETE_FAIL";

export const SCHEDULE_EDIT_REQUEST = "SCHEDULE_EDIT_REQUEST";
export const SCHEDULE_EDIT_SUCCESS = "SCHEDULE_EDIT_SUCCESS";
export const SCHEDULE_EDIT_FAIL = "SCHEDULE_EDIT_FAIL";
