export const SCHOOL_ADD_REQUEST = "SCHOOL_ADD_REQUEST";
export const SCHOOL_ADD_SUCCESS = "SCHOOL_ADD_SUCCESS";
export const SCHOOL_ADD_FAIL = "SCHOOL_ADD_FAIL";
export const SCHOOL_ADD_RESET = "SCHOOL_ADD_RESET";

export const SCHOOL_GET_REQUEST = "SCHOOL_GET_REQUEST";
export const SCHOOL_GET_SUCCESS = "SCHOOL_GET_SUCCESS";
export const SCHOOL_GET_FAIL = "SCHOOL_GET_FAIL";
export const SCHOOL_GET_RESET = "SCHOOL_GET_RESET";

export const SCHOOL_PARTICULAR_REQUEST = "SCHOOL_PARTICULAR_REQUEST";
export const SCHOOL_PARTICULAR_SUCCESS = "SCHOOL_PARTICULAR_SUCCESS";
export const SCHOOL_PARTICULAR_FAIL = "SCHOOL_PARTICULAR_FAIL";
export const SCHOOL_PARTICULAR_RESET = "SCHOOL_PARTICULAR_RESET";

export const SCHOOL_EDIT_REQUEST = "SCHOOL_EDIT_REQUEST";
export const SCHOOL_EDIT_SUCCESS = "SCHOOL_EDIT_SUCCESS";
export const SCHOOL_EDIT_FAIL = "SCHOOL_EDIT_FAIL";
export const SCHOOL_EDIT_RESET = "SCHOOL_EDIT_RESET";

export const SCHOOL_GET_ADMIN_REQUEST = "SCHOOL_GET_ADMIN_REQUEST";
export const SCHOOL_GET_ADMIN_SUCCESS = "SCHOOL_GET_ADMIN_SUCCESS";
export const SCHOOL_GET_ADMIN_FAIL = "SCHOOL_GET_ADMIN_FAIL";
export const SCHOOL_GET_ADMIN_RESET = "SCHOOL_GET_ADMIN_RESET";

export const STUDENTS_GET_REQUEST = "STUDENTS_GET_REQUEST";
export const STUDENTS_GET_SUCCESS = "STUDENTS_GET_SUCCESS";
export const STUDENTS_GET_FAIL = "STUDENTS_GET_FAIL";
export const STUDENTS_GET_RESET = "STUDENTS_GET_RESET";
